---
- name: Copy a ls22sistem.pub key
  ansible.builtin.copy:
    src: /home/ls22sistem/.ssh/ls22sistem.pub
    dest: /home/ls22sistem/backups/ls22sistem.pub
    owner: ls22sistem
    group: ls22sistem
    mode: 0700
    backup: yes
    remote_src: yes

- name: Copy a ls22web.pub key
  ansible.builtin.copy:
    src: /home/ls22web/.ssh/ls22web.pub
    dest: /home/ls22sistem/backups/ls22web.pub
    owner: ls22web
    group: ls22web
    mode: 0700
    backup: yes
    remote_src: yes

- name: Copy a ls22th.pub key
  ansible.builtin.copy:
    src: /home/ls22th/.ssh/ls22th.pub
    dest: /home/ls22sistem/backups/ls22th.pub
    owner: ls22th
    group: ls22th
    mode: 0700
    backup: yes
    remote_src: yes
