---
####### ansible_user .ssh managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place {{ansible_user}}"
  file:
      state: directory
      path: "/home/{{ansible_user}}/.ssh"
      recurse: yes
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: "0700"

- name: "Access - Push Public ssh key {{ansible_user}}"
  copy:
      src: "../templates/ls22sistem.pub"
      dest: "/home/{{ansible_user}}/.ssh/"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: "0600"


####### web user .kk managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place {{web_user}}"
  file:
      state: directory
      path: "/home/{{web_user}}/.ssh"
      recurse: yes
      owner: "{{web_user}}"
      group: "{{web_user}}"
      mode: "0700"

- name: "Access - Push Public ssh key {{web_user}}"
  copy:
      src: "../templates/ls22web.pub"
      dest: "/home/{{web_user}}/.ssh/"
      owner: "{{web_user}}"
      group: "{{web_user}}"
      mode: "0600"


####### th user .ssh managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place {{th_user}}"
  file:
      state: directory
      path: "/home/{{th_user}}/.ssh"
      recurse: yes
      owner: "{{th_user}}"
      group: "{{th_user}}"
      mode: "0700"

- name: "Access - Push Public ssh key {{th_user}}"
  copy:
      src: "../templates/ls22th.pub"
      dest: "/home/{{th_user}}/.ssh/"
      owner: "{{th_user}}"
      group: "{{th_user}}"
      mode: "0600"


####### root .ssh managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place root"
  file:
      state: directory
      path: "/home/root/.ssh"
      recurse: yes
      owner: "root"
      group: "root"
      mode: "0700"

- name: "Access - Push Public ssh key {{ansible_user}}"
  copy:
      src: "../templates/ls22sistem.pub"
      dest: "/home/{{ansible_user}}/.ssh/"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: "0600"

#değiştirildi.
#- name: "Access - Push Public ssh key {{th_user}}"
#  template:
#      src: "../templates/ls22thr.pub.j2"
#      dest: "/home/{{th_user}}/.ssh"
#      user: "{{th_user}}"
#      state: present
#      key: "{{ lookup('file', '../keys/ls22ahtapot.pub') }}"
#      owner: "{{ th_user}}"
#      group: "{{ th_user }}"
#      mode: 640
#- name: Access - Push Public ssh key
#  authorized_key:
#      user: "{{th_user}}"
#      state: present
#      key: "{{ lookup('file', '../templates/ls21th.pub') }}"
#
#- name: "File Permissions - home directory .ssh permissions"
#  shell: chown -R "{{th_user}}":"{{th_user}}" /home/{{th_user}}/.ssh
#  shell: chmod 600 /home/{{th_user}}/.ssh/ls21th.pub
