---
# LS21-LS22 Linux Operation Security
# Selin Akbuğa
# Configure basics of linux machines: users, passwords, home file permissions, ssh key directory

- name: "Setup - Create group {{ansible_user}}"
  group:
      name: "{{ansible_user}}"

- name: "Setup - Create user {{ansible_user}} (Debian-ish)"
  user:
      name: "{{ansible_user}}"
      groups: "{{ansible_user}},sudo"
      append: yes
      shell: /bin/bash
      createhome: yes
#      password: "{{ 'ahtapot.123!!' |password_hash( 'sha512') }}"
      password: "{{deb_ansible_pass}}"
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: "Setup - Create user {{ansible_user}} (RedHat-ish)"
  user:
      name: "{{ansible_user}}"
      groups: "{{ansible_user}},wheel"
      append: yes
      shell: /bin/bash
      createhome: yes
      home: /home/{{ansible_user}}
#      password: "{{ 'ahtapot.123!!' |password_hash( 'sha512') }}"
      password: "{{yum_ansible_pass}}"
  when: ansible_distribution in ['RedHat', 'CentOS', 'AlmaLinux']

- name: "File Permissions - {{ansible_user}} home directory permissions"
  shell: chown -R "{{ansible_user}}":"{{ansible_user}}" /home/{{ansible_user}}
  shell: chmod 750 /home/{{ansible_user}}

- name: "Recursively change ownership of a {{ansible_user}} home directory"
  file:
      path: "/home/{{ansible_user}}"
      state: directory
      recurse: yes
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"

#######web user tasks

- name: "Setup - create group {{web_user}}"
  group:
    name: "{{web_user}}"

- name: "Setup - Create user {{web_user}} (Debian-ish)"
  user:
      name: "{{web_user}}"
      groups: "{{web_user}},sudo"
      append: yes
      shell: /bin/bash
      createhome: yes
      password: "{{deb_web_pass}}"
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: "Setup - Create user {{web_user}} (RedHat-ish)"
  user:
      name: "{{web_user}}"
      groups: "{{web_user}},wheel"
      append: yes
      shell: /bin/bash
      createhome: yes
      home: /home/{{web_user}}
      password: "{{yum_web_pass}}"
  when: ansible_distribution in ['RedHat', 'CentOS', 'AlmaLinux']

- name: "File Permissions - {{web_user}} home directory permissions"
  shell: chown -R "{{web_user}}":"{{ansible_user}}" /home/{{web_user}}
  shell: chmod 750 /home/{{web_user}}

- name: "Recursively change ownership of a {{web_user}} home directory"
  file:
      path: "/home/{{web_user}}"
      state: directory
      recurse: yes
      owner: "{{web_user}}"
      group: "{{web_user}}"

####### th user managment

- name: "Setup - create group {{th_user}}"
  group:
    name: "{{th_user}}"

- name: "Setup - Create user {{th_user}} (Debian-ish)"
  user:
      name: "{{th_user}}"
      groups: "{{th_user}},sudo"
      append: yes
      shell: /bin/bash
      createhome: yes
      password: "{{deb_th_pass}}"
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: "Setup - Create user {{th_user}} (RedHat-ish)"
  user:
      name: "{{th_user}}"
      groups: "{{th_user}},wheel"
      append: yes
      shell: /bin/bash
      createhome: yes
      home: /home/{{th_user}}
      password: "{{yum_th_pass}}"
  when: ansible_distribution in ['RedHat', 'CentOS', 'AlmaLinux']

- name: "File Permissions - {{th_user}} home directory permissions"
  shell: chown -R "{{th_user}}":"{{th_user}}" /home/{{th_user}}
  shell: chmod 750 /home/{{th_user}}

- name: "Recursively change ownership of a {{th_user}} home directory"
  file:
      path: "/home/{{th_user}}"
      state: directory
      recurse: yes
      owner: "{{th_user}}"
      group: "{{th_user}}"

###root managment keys

- name: Change user password
  user:
      name: root
      update_password: always
      password: "{{ deneme |password_hash('sha512') }}"

#- name: "Access - Change root password  (Debian-ish)"
#  user:
#      name: "root"
#      password: "{{deb_root_pass}}"
#  when: ansible_distribution in ['Debian', 'Ubuntu']
#
#- name: "Access - Change root password  (RedHat-ish)"
#  user:
#      name: "root"
#      password: "{{yum_root_pass}}"
#  when: ansible_distribution in ['RedHat', 'CentOS', 'AlmaLinux']

