---
- name:
  get_url:
    url: '{{ item.link }}'
    dest: '{{ item.dest }}'
    mode: '0770'
    timeout: 20
  with_items:
    - { link: https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.17-rc7/amd64/linux-image-unsigned-5.17.0-051700rc7-generic_5.17.0-051700rc7.202203062330_amd64.deb, dest: /opt/image.deb }
    - { link: https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.17-rc7/amd64/linux-modules-5.17.0-051700rc7-generic_5.17.0-051700rc7.202203062330_amd64.deb, dest: /opt/modules.deb }

- name: Install deb packages
  command: 
    cmd: dpkg -i /opt/image.deb /opt/modules.deb
