---
- hosts: all
  gather_facts: yes
  become: True
  become_user: root
  roles:
    - ../roles/01_user_managment
    - ../roles/user_change_password
    - ../roles/00_quick_env_info
    - ../roles/install-package
